---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0001
    labels:
      type: local
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/tmp/data01"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mysql-data
    labels:
      type: local
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
